
stages:
  split:
    cmd: python src/data/preproc_split.py
    deps:
    - src/data/preproc_split.py
    process_external_data:
      - data/raw_data/raw.csv 
    outs:
    - data/processed_data/X_train.csv
    - data/processed_data/X_test.csv
    - data/processed_data/y_train.csv
    - data/processed_data/y_test.csv
  normalize:
    cmd: python src/data/preproc_norm.py
    deps:
    - data/processed_data/X_train.csv
    - data/processed_data/X_test.csv
    - src/data/preproc_norm.py
    outs:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/X_test_scaled.csv
  gridsearch:
    cmd: python src/models/model_gridsearch.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - src/models/model_gridsearch.py
    outs:
    - models/best_params_RFReg.pkl
  train:
    cmd: python src/models/model_train.py
    deps:
    - models/best_params_RFReg.pkl
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - src/models/model_train.py
    outs:
    - models/RandomForestRegressor_model.pkl
  evaluate:
    cmd: python src/models/model_eval.py
    deps:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/y_test.csv
    - models/RandomForestRegressor_model.pkl
    - src/models/model_eval.py
    outs:
    - data/processed_data/predictions.csv
    metrics:
    - metrics/evaluation_results.json
    